"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import QRCode from "qrcode";
const COLORS=["#6d3ae5","#ed4f8b","#f59e0b","#168866","#1689c8","#e34a3f","#8b5cf6","#14a69a","#d76b20","#4765d8","#bc3f79","#508b36"],DEFAULTS=["小明","小華","小美","小安","小傑","小琪"];
type Mode="repeat"|"remove"|"no-consecutive";
export default function LuckyWheel(){
 const canvas=useRef<HTMLCanvasElement>(null),result=useRef<HTMLDialogElement>(null),shareBox=useRef<HTMLDialogElement>(null),rotation=useRef(0),spinning=useRef(false),last=useRef<string|null>(null),audio=useRef<AudioContext|null>(null);
 const [soundOn,setSoundOn]=useState(true);
 const [tab,setTab]=useState<"text"|"number">("text"),[text,setText]=useState(DEFAULTS.join("\n")),[items,setItems]=useState(DEFAULTS),[original,setOriginal]=useState(DEFAULTS),[mode,setMode]=useState<Mode>("repeat"),[history,setHistory]=useState<string[]>([]),[winner,setWinner]=useState(""),[status,setStatus]=useState("目前有 6 個項目，可以開始抽選！"),[range,setRange]=useState([1,20,1]),[url,setUrl]=useState(""),[qr,setQr]=useState(""),[toast,setToast]=useState("");
 const parsed=text.split(/\r?\n|,|，/).map(x=>x.trim()).filter(Boolean).slice(0,300);
 const draw=useCallback((list=items)=>{const c=canvas.current,x=c?.getContext("2d");if(!c||!x)return;const w=c.width,m=w/2,r=w*.465,n=list.length;x.clearRect(0,0,w,w);x.save();x.translate(m,m);if(!n){x.beginPath();x.arc(0,0,r,0,Math.PI*2);x.fillStyle="#ddd8d2";x.fill();x.fillStyle="#716b7e";x.textAlign="center";x.font="700 27px sans-serif";x.fillText("請加入抽選項目",0,8);x.restore();return}const arc=Math.PI*2/n;x.rotate(rotation.current-Math.PI/2);list.forEach((label,i)=>{x.beginPath();x.moveTo(0,0);x.arc(0,0,r,i*arc,(i+1)*arc);x.closePath();x.fillStyle=COLORS[i%COLORS.length];x.fill();x.strokeStyle="#fff";x.lineWidth=n>80?1:3;x.stroke();if(n<=70){x.save();x.rotate((i+.5)*arc);x.textAlign="right";x.textBaseline="middle";x.fillStyle="#fff";x.font=`800 ${Math.max(12,Math.min(30,610/n))}px sans-serif`;x.fillText(label.length>18?label.slice(0,17)+"…":label,r-25,0);x.restore()}});x.beginPath();x.arc(0,0,r*.135,0,Math.PI*2);x.fillStyle="#fffdf9";x.fill();x.lineWidth=9;x.strokeStyle="#e9e3ed";x.stroke();x.restore()},[items]);
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem("luckyWheelV3")||"null");if(s?.list?.length){const l=s.list.map(String);setItems(l);setOriginal(l);setText(l.join("\n"));setMode(s.mode||"repeat")}}catch{}setUrl(location.href.split("#")[0])},[]);useEffect(()=>draw(),[draw]);useEffect(()=>{if(url)QRCode.toDataURL(url,{width:720,margin:2,color:{dark:"#1d1830",light:"#fff"}}).then(setQr)},[url]);
 const save=(list:string[],m=mode)=>{try{localStorage.setItem("luckyWheelV3",JSON.stringify({list,mode:m}))}catch{}};
 const apply=(list=parsed)=>{if(!list.length){setStatus("請先輸入至少一個項目。");return}setItems(list);setOriginal(list);setText(list.join("\n"));setHistory([]);last.current=null;rotation.current=0;save(list);setStatus(`已套用 ${list.length} 個項目，可以開始抽選！`);setTimeout(()=>draw(list),0)};
 const makeNumbers=()=>{const [a,b,s]=range;if(!Number.isFinite(a)||!Number.isFinite(b)||!Number.isFinite(s)||s<=0){setStatus("請輸入有效的數字範圍。");return}const d=a<=b?1:-1,out:string[]=[];for(let v=a;d>0?v<=b+s/1e6:v>=b-s/1e6;v+=d*s){out.push(String(+v.toFixed(10)));if(out.length>=300)break}apply(out)};
 const fanfare=()=>{if(!soundOn)return;const a=audio.current;if(!a)return;const now=a.currentTime,master=a.createGain(),compressor=a.createDynamicsCompressor();master.gain.setValueAtTime(.42,now);master.gain.exponentialRampToValueAtTime(.001,now+2.8);compressor.threshold.value=-16;compressor.ratio.value=5;master.connect(compressor).connect(a.destination);const notes=[[523.25,0,.2],[659.25,.18,.2],[783.99,.36,.28],[1046.5,.65,.65],[783.99,1.35,.2],[1046.5,1.55,.8]];notes.forEach(([freq,delay,duration],i)=>{[0,1].forEach(layer=>{const o=a.createOscillator(),g=a.createGain(),filter=a.createBiquadFilter(),t=now+delay+layer*.008;o.type=layer?"square":"sawtooth";o.frequency.setValueAtTime(freq*(layer?2:1),t);filter.type="lowpass";filter.frequency.setValueAtTime(2200,t);filter.Q.value=2.5;g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(layer?.025:.13,t+.025);g.gain.setValueAtTime(layer?.025:.13,t+duration*.72);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(filter).connect(g).connect(master);o.start(t);o.stop(t+duration+.03)});if(i===3||i===5){const o=a.createOscillator(),g=a.createGain(),t=now+delay;o.type="sine";o.frequency.setValueAtTime(freq/2,t);g.gain.setValueAtTime(.08,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g).connect(master);o.start(t);o.stop(t+duration)}})};
 useEffect(()=>{const unlock=()=>{audio.current??=new AudioContext();if(audio.current.state==="suspended")audio.current.resume()};addEventListener("pointerdown",unlock,{once:true});const dialog=result.current;if(!dialog)return()=>removeEventListener("pointerdown",unlock);const observer=new MutationObserver(()=>{if(dialog.hasAttribute("open"))fanfare()});observer.observe(dialog,{attributes:true,attributeFilter:["open"]});return()=>{observer.disconnect();removeEventListener("pointerdown",unlock)}},[soundOn]);
 const wheelSound=()=>{if(!soundOn)return;audio.current??=new AudioContext();const a=audio.current;if(a.state==="suspended")a.resume();let delay=0;for(let i=0;i<40&&delay<3.02;i++){const p=i/39,o=a.createOscillator(),g=a.createGain(),filter=a.createBiquadFilter(),t=a.currentTime+delay;o.type="square";o.frequency.setValueAtTime(980-520*p,t);filter.type="bandpass";filter.frequency.value=1200-500*p;filter.Q.value=1.8;g.gain.setValueAtTime(.055*(1-p*.3),t);g.gain.exponentialRampToValueAtTime(.001,t+.025+.018*p);o.connect(filter).connect(g).connect(a.destination);o.start(t);o.stop(t+.05);delay+=.038+.105*p*p}};
 useEffect(()=>{const click=(e:MouseEvent)=>{const button=(e.target as HTMLElement).closest("button.spin") as HTMLButtonElement|null;if(button&&!button.disabled)wheelSound()};const key=(e:KeyboardEvent)=>{if(e.code==="Space"&&!(["INPUT","TEXTAREA","BUTTON"].includes((document.activeElement as HTMLElement)?.tagName)))wheelSound()};addEventListener("click",click);addEventListener("keydown",key);return()=>{removeEventListener("click",click);removeEventListener("keydown",key)}},[soundOn]);
 const spin=()=>{if(spinning.current||!items.length)return;spinning.current=true;let choices=items.map((_,i)=>i);if(mode==="no-consecutive"&&items.length>1&&last.current)choices=choices.filter(i=>items[i]!==last.current);const chosen=choices[Math.floor(Math.random()*choices.length)],arc=Math.PI*2/items.length,final=((Math.PI*2-(chosen+.5)*arc)%(Math.PI*2)+Math.PI*2)%(Math.PI*2),current=((rotation.current%(Math.PI*2))+Math.PI*2)%(Math.PI*2);let delta=final-current;if(delta<0)delta+=Math.PI*2;const from=rotation.current,target=from+7*Math.PI*2+delta,t0=performance.now();const frame=(now:number)=>{const p=Math.min(1,(now-t0)/3100);rotation.current=from+(target-from)*(1-Math.pow(1-p,4));draw(items);if(p<1)return requestAnimationFrame(frame);rotation.current%=Math.PI*2;const picked=items[chosen];last.current=picked;setWinner(picked);setHistory(h=>[picked,...h]);result.current?.showModal();if(mode==="remove"){const next=items.filter((_,i)=>i!==chosen);setItems(next);setStatus(next.length?`抽中「${picked}」，還有 ${next.length} 個項目。`:`抽中「${picked}」，所有項目已抽完。`);setTimeout(()=>draw(next),0)}else setStatus(`抽中「${picked}」！`);spinning.current=false};requestAnimationFrame(frame)};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.code==="Space"&&!(["INPUT","TEXTAREA","BUTTON"].includes((document.activeElement as HTMLElement)?.tagName))){e.preventDefault();spin()}};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)});
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),1800)},copy=async()=>{await navigator.clipboard.writeText(url);notify("連結已複製")},share=async()=>navigator.share?navigator.share({title:"幸運轉盤",text:"一起來轉幸運轉盤！",url}):copy(),download=()=>{const a=document.createElement("a");a.href=qr;a.download="幸運轉盤-QR-Code.png";a.click()};
 return <main className="app"><header className="top"><div><p className="eyebrow">LUCKY WHEEL</p><h1>幸運轉盤</h1><p className="sub">輸入名單，輕按一下，讓幸運替你做決定。</p></div><button className="share-open" onClick={()=>shareBox.current?.showModal()}>分享與 QR Code</button></header><section className="layout"><div className="card wheel-card"><div className="wheel-wrap"><div className="pointer"/><canvas ref={canvas} width="900" height="900" aria-label="幸運轉盤"/></div><button className="spin" onClick={spin} disabled={!items.length}>開始轉動</button><p className="hint">電腦可按空白鍵；手機與平板請點按按鈕</p></div><aside className="card panel"><h2>轉盤設定</h2><div className="tabs"><button className={tab==="text"?"active":""} onClick={()=>setTab("text")}>文字名單</button><button className={tab==="number"?"active":""} onClick={()=>setTab("number")}>數字範圍</button></div>{tab==="text"?<><label className="label" htmlFor="items">每行一個項目，也可用逗號分隔</label><textarea id="items" value={text} onChange={e=>setText(e.target.value)}/><div className="count"><span>最多 300 個項目</span><span>共 <b>{parsed.length}</b> 個</span></div></>:<><label className="label">建立數字範圍</label><div className="numbers">{["開始","結束","間隔"].map((x,i)=><label key={x}>{x}<input type="number" value={range[i]} min={i===2?0.000001:undefined} onChange={e=>setRange(r=>r.map((v,j)=>j===i?+e.target.value:v))}/></label>)}</div></>}<label className="label">抽選方式</label><div className="modes">{[["repeat","可重複抽選","每次都保留項目"],["remove","抽後移除","適合依序分組"],["no-consecutive","不連續重複","下次不抽到同項"]].map(([m,t,s])=><button key={m} className={mode===m?"active":""} onClick={()=>{setMode(m as Mode);save(original,m as Mode)}}>{t}<small>{s}</small></button>)}</div><button className="apply" onClick={()=>tab==="text"?apply():makeNumbers()}>{tab==="text"?"套用名單到轉盤":"建立並套用數字"}</button><div className="status" aria-live="polite">{status}</div><div className="history-title"><h3>抽選紀錄</h3><div><button onClick={()=>{setItems(original);setHistory([]);last.current=null;setStatus(`已恢復 ${original.length} 個項目。`)}}>恢復全部</button><button onClick={()=>setHistory([])}>清除</button></div></div><div className="chips">{history.length?history.map((x,i)=><span className="chip" key={`${x}-${i}`}>{history.length-i}. {x}</span>):<span className="empty">尚未抽選</span>}</div></aside></section><dialog ref={result}><div className="result"><div className="emoji">🎉</div><h3>恭喜抽中</h3><div className="winner">{winner}</div><button onClick={()=>result.current?.close()}>繼續抽選</button></div></dialog><dialog ref={shareBox}><div className="share-box"><h2>分享幸運轉盤</h2><p>掃描 QR Code，任何裝置都能開啟。</p>{qr&&<img className="qr" src={qr} alt="幸運轉盤網址 QR Code"/>}<div className="url">{url}</div><div className="share-actions"><button onClick={share}>分享／複製連結</button><button className="download" onClick={download}>下載 QR Code</button></div><button className="close-share" onClick={()=>shareBox.current?.close()}>關閉</button></div></dialog>{toast&&<div className="toast">{toast}</div>}</main>
}
